### ISSUE TITLE
Dependency Bump Needed

### ISSUE THREAD

**Issue by CooperW824** [hack-rpi/HackRPI-Website-2024#40]
Seems like there are a lot of dependencies that have had minor updates since this project started, we should bump the deps.

**Comment by Jordan231111** [comment]
I respectfully disagree that each dependency update needs its own pull request, it will just save time for both of us and reduce clutter

**Comment by CooperW824** [comment]
There are actually a few good arguments for doing dependency bumps as separate PRs rather than feature PRs. Here are 3 reasons why:

## 1. Reduces Bugs
If we create separate PRs for features and dependency bumps, its easier to debug before the site reaches production. Lets say we have a PR of a new feature that also goes and updates a bunch of dependencies. We notice that this PR introduces a new bug into our site. Since the PR is both a new feature and a dependency update, we aren't sure if its the new feature that's breaking things or possibly a dependency. If it is a dependency, well then we have to go one by one to find a fix. Doing dependency bumps in separate PRs allows us to isolate possible causes for bugs and do more testing, reducing the number of bugs that go into production.

## 2. Improves Compatibility
In our case, all of our dependency bumps are minor updates, and in theory, should have no breaking changes. But we don't know that for sure. Doing separate PRs for dependency bumps and features means that if for some reason a dependency introduces a new breaking change, its easier to catch, and revert if needed. 

## 3. Improves Security
Take the recent discovery of the backdoor that was introduced in the 5.6.0 version of xz, a dependency in OpenSSH. Let's say that something like that happens to one of our dependencies. Well of course we should roll back our change to ensure the best security for our users. However, if our update to this dependency is part of a feature PR, we then have to roll back the entire feature instead of just the dependency bump, which isn't always desirable.

Now of course these arguments are more relevant on bigger projects that more people rely on, but we should try to follow best practices when it comes to dependency bumps. Especially considering how important dependency management is for a project like this one (our project wouldn't be possible without these dependencies).

If you are looking for examples of this in production code, look no further than [Submitty](https://github.com/Submitty/Submitty/pulls). Where you can see a variety of PRs just for dependency bumps.

I am really glad you brought this question up, being able to have discussions like these make all open source projects better, and allows us to learn from each other's experience. In the future however, I would refrain from closing an issue because you disagree or feel its unnecessary, instead comment your thoughts, leave the issue open, and let others discuss too. Open source thrives on open communication and feedback. We can close issues when we deploy fixes or when we as a community come to the consensus that an issue can be closed or won't be fixed.
